apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-microservice
spec:
  title: Spring Microservices
  description: Spring Microservices getting started
  vendor: eduk8s.io
  difficulty: beginner
  duration: 30m
  url: github.com/everythingeverywhere/lab-microservice
  content:
    image: jdk11-environment:*
    files: github.com/everythingeverywhere/lab-microservice
  session:
    budget: large
    resources:
      memory: 2Gi
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
    
