apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-microservice
spec:
  title: Markdown Sample
  description: A sample workshop using Markdown
  vendor: eduk8s.io
  difficulty: beginner
  duration: 60m
  url: github.com/everythingeverywhere/lab-microservice
  content:
    image: quay.io/eduk8s/jdk8-environment:master
    files: github.com/everythingeverywhere/lab-microservice
  session:
    budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
